name = "noname-server"
main = "src/index.js"
compatibility_date = "2026-01-28"

routes = [
  { pattern = "play.quaternijkon.online/ws*", zone_name = "quaternijkon.online" }
]

workers_dev = true

[durable_objects]
bindings = [{ name = "LOBBY_DO", class_name = "LobbyDurableObject" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LobbyDurableObject"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
