name = "noname-server"
main = "src/index.js"
compatibility_date = "2026-01-28"

[durable_objects]
bindings = [{ name = "LOBBY_DO", class_name = "LobbyDurableObject" }]

[[migrations]]
tag = "v1"
new_classes = ["LobbyDurableObject"]
